<html>
<head></head>
<body>
<?php
echo <<< 'EOT'
<p>
This is a test php file, to test the parser generated by tscc-compiler.
see zend_language_parser.y for the grammar.
</p>
EOT;
function printSequence($a1, $a2, $n, $getNext){
    echo "<p>a1 = $a1</p>\n";
    for($i = 2; $i <= $n; $i++){
        echo "<p>a$i = $a2</p>\n";
        $a = $getNext($a1, $a2);
        $a1 = $a2;
        $a2 = $a;
    }
}
// fabonacci sequence
printSequence(1, 1, 20, function($a1, $a2){
    return $a1 + $a2;
});
function aaa(){
    return ['hkm' => '好嘛', 'soor' => '锁尔', '固定搭配' => ['rfnj' => '你肯定在']];
}
['hkm' => $hkm, 'soor' => $soor, '固定搭配' => ['rfnj' => $nkdz]] = aaa();
echo <<< EOT
<p>'hkm' = $hkm</p>
<p>'soor' = $soor</p>
<p>'nkdz' = $nkdz</p>
EOT;
$c = getTestObject();
echo "test = $c->test\n";
$c->setProp('rfnj');
echo "test = $c->test\n";
?>
</body>
</html>